# Generated by Django 5.2.4 on 2025-07-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authCustom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
