# Generated by Django 5.2.4 on 2025-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_department_created_at_department_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('password', 'Password'), ('boolean', 'Boolean'), ('select', 'Dropdown'), ('textarea', 'Multiline'), ('file', 'File Upload')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeefielddata',
            name='value',
            field=models.JSONField(),
        ),
    ]
