# Generated by Django 5.2.4 on 2025-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_dynamicfield_field_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('password', 'Password'), ('boolean', 'Boolean'), ('select', 'Dropdown'), ('textarea', 'Multiline')], max_length=20),
        ),
    ]
